
export const projects = [
  {
    title: 'Weather App',
    description: "A weather app to look up the weather in the area you want to see.",
    image: '/images/1.png',
    tags: ['React | ' + 'TailwindCSS | ' + 'Toastify  '],
    visit: 'https://github.com/mikeydgithub/weather_app',
    source: 'https://weatherzone22-app.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Pizza Hunt',
    description:"A social network pizza app that users can create pizzas, save their orders, and start a discussion.",
    image: '/images/2.png',
    tags: ['Mongoose | ' + 'Node.js | ' + 'Express '],
    visit: 'https://github.com/mikeydgithub/pizza-hunt',
    source: 'https://pizza-hunt22.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Travel Budget Tracker',
    description: "A PWA (Progress Web Application) for tracking your vacation budget with slow internet or no internet.",
      image: '/images/3.png',
      tags: ['Compression | ' + 'Mongoose | ' + 'Morgan | ' + 'Express '],
    visit: 'https://github.com/mikeydgithub/Travel-Budget-Tracker',
    source: 'https://travel-budget-trackerv1.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Pokemon App',
    description: "An app for generating a pokemon based on how many github repositories the user has.",
    image: '/images/4.png',
    tags: ['JavaScript | ' + 'Materialize | '+ 'HTML | '+ 'CSS'],
    visit: 'https://github.com/mikeydgithub/Pokemon-App',
    source: 'https://mikeydgithub.github.io/Pokemon-App/',
    id: 3,
  },
  {
    title: 'Crypto CLI',
    description: "An app using a fetch API from CoinGecko to display real time prices in your CLI with color.",
    image: '/images/5.png',
    tags: ['React | ' + 'Axios | '+ 'Ink | '+ 'Meow '],
    vist: 'https://github.com/mikeydgithub/crypto-InkCLI',
    source: 'https://github.com/mikeydgithub/crypto-InkCLI',
    id: 4,
  },
  {
    title: 'Shop Shop',
    description: "An E-Commerce app for purchasing house hold items and food.",
    image: '/images/6.png',
    tags: ['React | ' + 'Stripe | '+ 'React-Router | '+ 'Mongoose | ' + 'GraphQL | ' + 'JWT '],
    vist: 'https://github.com/mikeydgithub/shop-shop',
    source: 'https://shoper-shop-app.herokuapp.com/',
    id: 5,
  },
];
